### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ad3429** [Estee25/prj-rev-bwfs-tea-cozy#5]
**Summary Grade: Satisfactory**

Good job! Your files are organized nicely, and you did a great job of matching the client specification for the most part -- this is an important skill to have as a developer and you seem to understand that. Moreover, you generally followed excellent code practice, so make sure to keep that up!

I have made some comments in your code to take note of. First off, good job commenting the main parts of your HTML and CSS. This practice goes a long way as your projects get larger and more complex. You can even comment your CSS further so that it's absolutely clear why you decided to style elements a particular way. This becomes increasingly important as your projects get larger and more complex. Your code is also very nicely structured/formatted and follows excellent code practices such as readability, indentation, etc. Overall, you did a great job and I do not have negative things to say. 

Next off, this isn't a big issue now since you haven't learned about this yet, but I wanted to introduce you to the idea of responsive design. You will learn more about this concept in the next project, but I wanted to provide a great resource to get you to start thinking about building sites that look good on all different kinds of platforms/browser sizes:

https://www.w3schools.com/css/css_responsive_intro.asp

Great job overall! As a further challenge, try using css to design your webpage even further! You did a great job in following the client specification, but for your own practice you should see how creative you can get by taking the design/styling of your site to the next level (for example, you can try experimenting with background colors on your other divs.

**Comment by Estee25** [comment]
Thank you for the review and positive comments. I will continue learning happily. Regarding responsive design, I will read the link you provided as already stuck with Unit5.. Thank you.
